name: ESLint

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Code Linting
      run: npm run lint
